### ISSUE TITLE
The h2 tags in row should be inside the row container

### ISSUE THREAD

**Issue by animeshsinghweb** [fossasia/gci16.fossasia.org#506] opened 2016-12-13 11:21 UTC
The `<h2>` tag should be inside the container, it is killing the UI and UX..

![image](https://cloud.githubusercontent.com/assets/16618931/21138475/3ed3bf3a-c154-11e6-96f6-0d1d1dcbdfdc.png)

**Comment by abishekvashok** [comment] 2016-12-13 11:51
@animeshsinghweb it's easy would you like to work on it.

**Comment by codein-dwij** [comment] 2016-12-13 11:52
You are having some issues with your browser.
![screenshot_1](https://cloud.githubusercontent.com/assets/16368363/21139392/a62d5656-c158-11e6-9fbb-3ba1d7f5f7ac.png)
It seems fine to me and is different from the one you have showed. 

Ping @animeshsinghweb 

I am closing this as the issue is not with the code

**Comment by animeshsinghweb** [comment] 2016-12-13 11:52
@Abhi2424shek I'm working on it. :)

**Comment by animeshsinghweb** [comment] 2016-12-13 11:55
@codein-dwij I know, I was using **Inspect Element** when I took the screenshot, all I want that is to be inside of `.row`.
Here is what I am working on:
![image](https://cloud.githubusercontent.com/assets/16618931/21139493/256954e2-c159-11e6-916f-a57f9235dea6.png)

**Comment by animeshsinghweb** [comment] 2016-12-13 11:57
@codein-dwij Why are you closing this mate?
This issue hasn't yet being resolved. Bear a while :running_woman:  :)

**Comment by codein-dwij** [comment] 2016-12-13 12:01
But isn't the present one looking better ?

**Comment by ankitrgadiya** [comment] 2016-12-13 12:03
It's not a mistake I did it intentionally but if you find it not good then sure go ahead. Open Source! :-) @animeshsinghweb 
Also I did the color intentionally and box shadow thing. You know, the header is having a static shadow but the container is having a transition with hover for box shadow to improve the UI

**Comment by animeshsinghweb** [comment] 2016-12-13 12:15
@ankitrgadiya  For sure :D

**Comment by codein-dwij** [comment] 2016-12-13 13:43
Fixed :)

**Closed as completed by codein-dwij** 2016-12-13 13:43 UTC
Labels: bug, ui/ux

**Comment by animeshsinghweb** [comment] 2016-12-13 13:45
@codein-dwij Yo! xD 👍

**Comment by codein-dwij** [comment] 2016-12-13 13:45
@animeshsinghweb  How did you merge your own commit?

**Comment by animeshsinghweb** [comment] 2016-12-13 13:48
@codein-dwij I'm even moderator at this repo, so I can merge your PR even, if there are no conflicts and satisfy the terms. 👍

**Comment by codein-dwij** [comment] 2016-12-13 13:51
@animeshsinghweb If you read , maintainers can merge their own PR's after 24hrs(one day) ONLY

**Comment by animeshsinghweb** [comment] 2016-12-13 16:11
@codein-dwij I accept my fault, I was about to go somewhere, and I didn't want merge conflicts when I come back. You know `lazy techies`.

**Comment by codein-dwij** [comment] 2016-12-13 16:19
@animeshsinghweb
 lol lol its ok..
