### ISSUE TITLE
Remove some space errors

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#235] opened 2016-12-06 08:29 UTC
We delay PRs because someone has a space at the end of a line - which is hard to understand and find and harmless.

Please remove the following errors:

- No newline at EOF
- Trailing whitespaces

**Comment by hoangvanthien** [comment] 2016-12-06 08:54
[Deleted]

**Comment by animeshsinghweb** [comment] 2016-12-07 12:10
Yeah, actually I founded that travis was causing space inconsistencies problem due to the this new line/space at EOF, and the message was pretty hard to guess what's actually wrong and I was having trouble understand that. But I just founded out that few peoples are just leaving an extra line at the end of CSSand it caused no errors. Maybe there is some issues with this.

**Comment by abishekvashok** [comment] 2016-12-08 11:42
The space inconsistency bear suggests that at the end of the page there should be an empty line as the POSIX standard says so. @niccokunzmannn some text editors automatically implement this. We could inform the students in the read me.

**Comment by jigyasa-grover** [comment] 2016-12-08 11:51
>We could inform the students in the read me.

@Abhi2424shek +1

**Comment by abishekvashok** [comment] 2016-12-08 13:54
@jig08 so should I give  PR or you guys would do it,

**Comment by m1guelpf** [comment] 2016-12-08 13:55
What about setting that in a .editorconfig file?

**Comment by abishekvashok** [comment] 2016-12-08 14:04
@m1guelpf have I forgot even that? wow, I worked with it for a project for intel, would give in a PR soon or will u be wanting to work.

**Comment by m1guelpf** [comment] 2016-12-08 14:06
@Abhi2424shek I have never worked with .editorconfig files, but if you can't do it, I'll try.

**Comment by abishekvashok** [comment] 2016-12-08 14:11
@m1guelpf I would give in a PR steady fast.

**Comment by m1guelpf** [comment] 2016-12-08 19:46
@Abhi2424shek How's going?

**Comment by abishekvashok** [comment] 2016-12-09 10:11
@m1guelpf I would post one today a bit busy.

**Comment by hemantjadon** [comment] 2016-12-09 18:05
@Abhi2424shek @Princu7 @m1guelpf 
Don't you think writing `.editorconfig` is not gonna solve all the problem completely though It will help on the editors with compatible plugins installed, like I know many of the main text editors do not support this directly (atom, vscode, vs studio, sublime, textmate, notepad++, xcode) all require an extra plugin to be installed. Mainly JetBeans IDE support this natively.

So though this is a right step, I think it is not a complete solution.

**Comment by abishekvashok** [comment] 2016-12-10 04:27
@hemantjadon sure, we will work on more solutions to go forward .editor config can be supported by additional plugins though, but the problem is the new developers won't have them. So we need something more rational. But I added editor config so that at least half of the people could be beneficial.

**Comment by hemantjadon** [comment] 2016-12-10 06:39
@Abhi2424shek Yes that's what i was mentioning. :)

**Comment by abishekvashok** [comment] 2016-12-10 07:26
@hemantjadon by the way atom has those by default (new line at EOF) let me see what else can I do...

**Comment by hemantjadon** [comment] 2016-12-10 07:58
@Abhi2424shek Oh i didn't knew that, but it doesn't support `.editorconfig` natively i guess?

**Comment by abishekvashok** [comment] 2016-12-10 08:07
No it doesn't have the support

**Comment by abishekvashok** [comment] 2016-12-10 16:47
I got a rational solution @niccokunzmann see issue #226

**Comment by jigyasa-grover** [comment] 2016-12-11 07:39
Update on this ?

**Comment by abishekvashok** [comment] 2016-12-11 07:45
@jig08 I opened a new Issue please see #414

**Comment by rhemon** [comment] 2016-12-11 08:00
I suggest we add some instruction on README/CONTRIBUTING on how to add and edit code so that build check pass. Beginners like me have very little knowledge related to all the space inconsistence and how tabs and spaces can cause difference. Therefore it would be really helpful for them to have a set of guideline to follow. That way they can avoid this errors. A link to those guidelines could be added to Tasks so that they know something like that exist. 

Also it would be informative and educational if there is also explanation for each of the checks.

**Comment by abishekvashok** [comment] 2016-12-11 08:11
@rhemon It would be informational nice suggestion +1

**Comment by abishekvashok** [comment] 2016-12-19 11:19
would be resolved in #599 so we could close this after it is merged.

**Comment by abishekvashok** [comment] 2016-12-20 08:30
Coala resolved the issue for us!

**Closed as completed by abishekvashok** 2016-12-20 08:30 UTC
Labels: bug, enhancement
